--- !ruby/object:Jumpstart::Configuration
application_name: National Fever Tracker
business_name: Public Art, LLC
domain: nationalfevertracker.com
support_email: support@mail.nationalfevertracker.com
default_from_email: National Fever Tracker <noreply@mail.nationalfevertracker.com>
business_address: |-
  110 E 13th St
  #3D
  New York, NY
background_job_processor: sidekiq
email_provider: postmark
integrations:
- honeybadger
